### ISSUE TITLE
Differences to Sycamore/Leptos/etc.

### ISSUE THREAD

**Issue by flosse** [silkenweb/silkenweb#35]
@simon-bourne it is nice to see that there is another fast framework existed by `Silkenweb`  :+1: 
As a curious new visitor, I wonder what is the main difference with other FRP based frameworks like `sycamore` or `leptops`.
I think it would be helpful to mention this in a short approach in the README.

BTW:
I really like the *"No Macro DSL"* approach :100:

**Comment by simon-bourne** [comment]
I agree, it would be good to have a comparison section in the README. I'll put some of my thoughts here to collect them first. Bear in mind that Leptos, Sycamore and Silkenweb are all changing fairly rapidly, and I don't know Sycamore or Leptos very well.

- Ecosystem: Silkenweb doesn't really have an ecosystem at this point, whereas Leptos and Syamore do.
- CSS: Silkenweb supports [CSS Modules](https://github.com/css-modules/css-modules). [Example](https://github.com/silkenweb/silkenweb/tree/main/examples/css-modules). The CSS support integrates well with SSR and Hydration.
- Server Functions: Leptos supports server functions which look great. Silkenweb doesn't support anything like this, but I did start work on some RPC stuff [here](https://github.com/simon-bourne/rust-rpc).
- Sycamore and Leptos both go to some effort to make cloning signals into closures more ergonomic. Silkenweb provides a `clone!` macro to make things a little easier, but otherwise doesn't address the problem. I'm not sure what the tradeoffs are for the Sycamore/Leptos solutions. Does it make cleaning up after derived signals harder? Does it mean more complex lifetime annotations?
- Silkenweb has support for using [third party web components](https://github.com/silkenweb/silkenweb/tree/main/examples/web-components-wrapper). I'm not sure about Sycamore or Leptos.
- Silkenweb has support for [shadow roots](https://github.com/silkenweb/silkenweb/tree/main/examples/shadow-root), including Hydration and SSR support with the experimental [Declarative Shadow DOM](https://web.dev/declarative-shadow-dom/). It also has a simple [Component](https://github.com/silkenweb/silkenweb/tree/main/examples/component) wrapper to manage slots. Again, I'm not sure about Leptos and Sycamore here.
- Silkenweb doesn't use any `unsafe` Rust directly. Some of the underlying Crates do use unsafe, but at least you don't have to put as much trust in my coding skills!
- As you mention, the biggest difference is that Silkenweb uses plain, non-macro Rust as much as possible. I believe Sycamore has a builder API as well, but I'm not sure.

**Comment by simon-bourne** [comment]
I've added a comparison section to the Readme. It's mostly just a re-wording of my comment above, but feel free to ask if there's anything else you want to know.
